import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,readFile,rm} from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {parseWooriPublic,fetchWooriPublic} from '../scripts/lib/woori-public.mjs';
const job={url:'https://pc.wooricard.com/ai-data/card_123456.html',name:'테스트 카드',card_type:'credit'};
const source=()=>({crd01DtlVo:{cdPrdCd:'123456',cdPrdNm:'테스트 카드',cdPrdCfcd:'1',cdTpDscd:'1'},crd01DtlBnfVoList:[{cdPrdBnfTxt:'온라인 할인',cdPrdBnfDtlTxt:'10% 할인'}],crd01DtlAmfeeVoList:[{amfeeAm:'10000'}],bdtCntnts:'전월 이용실적 30만원 이상'});
test('parses public API identity, fees, benefits and conditions without inventing tax facts',()=>{const {card}=parseWooriPublic(source(),job,'2026-09-21');assert.equal(card.annual_fee_krw,10000);assert.equal(card.benefits[0].rate_pct,10);assert.deepEqual(card.prev_month_spend_tiers_krw,[300000]);assert.equal(card.card_type,'credit');assert.match(card.source.url,/cdPrdCd=123456/);assert.equal(card.tax_counts_toward_spend,undefined);});
test('card type comes from product classification rather than physical-card type',()=>{const v=source();v.crd01DtlVo.cdPrdCfcd='2';assert.equal(parseWooriPublic(v,{...job,card_type:'check'},'2026-09-21').card.card_type,'check');assert.throws(()=>parseWooriPublic(v,job,'2026-09-21'),/type_mismatch/);});
test('rejects unknown type, identity mismatch and missing benefit data',()=>{for(const mutate of [v=>v.crd01DtlVo.cdPrdCfcd='9',v=>v.crd01DtlVo.cdPrdCd='999999',v=>v.crd01DtlVo.cdPrdNm='다른 카드',v=>v.crd01DtlBnfVoList=[]]){const v=source();mutate(v);assert.throws(()=>parseWooriPublic(v,job,'2026-09-21'));}});
test('cache stores only resultVo and preserves acquisition date/hash',async()=>{const dir=await mkdtemp(path.join(os.tmpdir(),'woori-test-'));try{let calls=0;const fetchImpl=async(url,opts)=>{calls++;assert.equal(opts.headers['Proworks-Body'],'Y');assert.equal(JSON.parse(opts.body).crd01DtlVo.cdPrdCd,'123456');return {ok:true,json:async()=>({elHeader:{resSuc:true,clientIp:'PRIVATE'},resultVo:source()})};};const first=await fetchWooriPublic(job,{cacheDir:dir,fetchImpl});const second=await fetchWooriPublic(job,{cacheDir:dir,fetchImpl});assert.equal(calls,1);assert.equal(second.responseEvidence.cacheHit,true);assert.equal(first.responseEvidence.sha256,second.responseEvidence.sha256);assert.equal(first.responseEvidence.retrievedAt,second.responseEvidence.retrievedAt);assert.doesNotMatch(await readFile(path.join(dir,'woori-public-123456.json'),'utf8'),/PRIVATE|elHeader/);}finally{await rm(dir,{recursive:true,force:true});}});
test('distinguishes eligible transaction amount from a discount amount cap',()=>{const v=source();v.bdtCntnts='<h2>온라인 할인</h2><p>결제 건당 최대 할인 대상 금액 5만원</p>';assert.equal(parseWooriPublic(v,job,'2026-09-21').card.benefits[0].per_txn_eligible_spend_cap_krw,50000);v.bdtCntnts='<h2>온라인 할인</h2><p>건당 최대 2,200원 청구할인</p>';assert.equal(parseWooriPublic(v,job,'2026-09-21').card.benefits[0].per_txn_eligible_spend_cap_krw,undefined);});
test('extracts a benefit-specific spend condition even with multiple page tiers',()=>{const v=source();v.crd01DtlBnfVoList[0].cdPrdBnfDtlTxt='전월실적 40만원 이상시 제공';v.bdtCntnts='전월실적 40만원 이상 또는 전월실적 80만원 이상';assert.equal(parseWooriPublic(v,job,'2026-09-21').card.benefits[0].requires_prev_month_spend_krw,400000);});
test('D4 corrects only verified discount amount caps and leaves input unchanged',async()=>{
  const {correctVerifiedWooriLegacy}=await import('../scripts/lib/woori-public.mjs');
  const rows=[{cdPrdBnfTxt:'33% 청구할인',cdPrdBnfDtlTxt:'시내버스, 지하철(후불교통기능 선택 시), 택시 건당 최대 2,200원 청구할인'},{cdPrdBnfTxt:'11% 청구할인',cdPrdBnfDtlTxt:'편의점 건당 할인한도 1,100원'}];
  const prev={issuer:'woori',name:'D4카드의정석Ⅱ',benefits:rows.map((r,i)=>({title:r.cdPrdBnfTxt,per_txn_eligible_spend_cap_krw:[2200,1100][i]}))};
  const next={...prev,product_url:'https://pc.wooricard.com/dcpc/yh1/crd/crd01/H1CRD101S02.do?cdPrdCd=103305',benefits:rows.map(r=>({title:r.cdPrdBnfTxt,summary:r.cdPrdBnfDtlTxt}))};
  const api={crd01DtlVo:{cdPrdCd:'103305',cdPrdNm:prev.name},crd01DtlBnfVoList:rows};
  const result=correctVerifiedWooriLegacy(prev,next,api);assert.equal(result.corrections.length,2);assert.equal(result.comparison.benefits[0].per_txn_eligible_spend_cap_krw,undefined);assert.equal(prev.benefits[0].per_txn_eligible_spend_cap_krw,2200);assert.equal(result.corrections[1].old_value,1100);assert.equal(result.corrections[0].exact_evidence,rows[0].cdPrdBnfDtlTxt);
  for(const change of [v=>v.crd01DtlVo.cdPrdCd='999999',v=>v.crd01DtlBnfVoList[0].cdPrdBnfDtlTxt='건당 최대 3,000원 청구할인',v=>v.crd01DtlBnfVoList[0].cdPrdBnfDtlTxt='결제 건당 최대 할인 대상 금액 2,200원']){const copy=structuredClone(api);change(copy);assert.equal(correctVerifiedWooriLegacy(prev,next,copy).corrections.some(c=>c.fieldpath==='benefits[0].per_txn_eligible_spend_cap_krw'),false);}
});
